version: '3'
services:
  frontend:
    build: ./api
    container_name: front
    restart: always
    ports:
      - 443:443
    volumes:
      - /app/node_modules #
      - ./api:/app
      - /app/.next #
  backend:
    build: ./backend
    container_name: backend
    restart: always
    ports:
      - 8888:8888
    volumes:
      - /app/node_modules #
      - ./backend:/app